version: 2.1

jobs:
  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - run: |
          ssh -oStrictHostKeyChecking=no -v ssh ubuntu@172.31.24.84 "./deploy.sh"

workflows:
  deploy-to-ec2:
    jobs:
      - deploy

