version: 2.1

jobs:
    deploy:
        docker:
            - image: arvindr226/alpine-ssh
        steps:
            - run: ssh -oStrictHostKeyChecking=no -v ubuntu@100.24.161.99 "./deploy.sh"

workflows:
    deploy-to-ec2:
        jobs:
            - deploy

