version: 2.1

jobs:
  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - name: Deploy to EC2
        run: ssh -oStrictHostKeyChecking=no -v ubuntu@ip-172-31-24-84 "./deploy.sh"

workflows:
  deploy-to-ec2:
    jobs:
      - deploy
